### PR TITLE
Update short description and logo

### PR DESCRIPTION
**Pull request by Julievrz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | update short description and logo
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes {https://github.com/PrestaShop/PrestaShop/issues/15858}.
| How to test?  | Please check that short description and logo are updated.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @Julievrz 
I have the new description but the logo that I found https://drive.google.com/drive/folders/1vaoyYz4LFRJr1cPM_T4D1cw4sI_cmneS is not updated for me.

See screenshot below:

Capture d’écran 2020-10-09 à 17 03 05

Thank you

**Comment by atomiix** [comment]
@ngodefroy It's probably because the old image has been cached by your browser. You should try to [force reload the page](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#:~:text=Google%20Chrome,-On%20Windows%20and&text=Hold%20the%20Ctrl%20key%20and%20press%20the%20R%20key.,button%20on%20the%20navigation%20toolbar.).

**Comment by Julievrz** [comment]
> Hello @Julievrz
> I have the new description but the logo that I found https://drive.google.com/drive/folders/1vaoyYz4LFRJr1cPM_T4D1cw4sI_cmneS is not updated for me.
> 
> See screenshot below:
> 
> Capture d’écran 2020-10-09 à 17 03 05
> 
> Thank you

image

I don't know why the logo didn't update as I changed it with the good one on the file.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
It's a browser cache issue. Keep in mind when you test a pull request to fully clear your browser cache, or use different subdomain/directory path each time you run a new test.
This one doesn't require QA and can be merge without it.

**Comment by PierreRambaud** [comment]
Thank you @Julievrz

**Pull request merged**
